version: '3.8'

services:

  postgresql:
    image: postgres:15
    container_name: postgresql
    
    #restart: unless-stopped  
    # 재부팅 후 자동 재시작. 수동으로 멈추면 재시작 안 함

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql 

    ports: 
      - "5432:5432"
      # 호스트:컨테이너

    volumes:  
      - postgresql-data:/var/lib/postgresql/data  

volumes:
  postgresql-data:
